customhost = "budgettracker.cxftipl0tzof.eu-central-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Suryaputra"
customdb = "employee"
custombucket = "add-bill-image"
customregion = "eu-central-1"
